server.port=${PORT:8080}

spring.datasource.url=${postgresql://biblioteca_fcmz_user:3EyfGBzSbUzADCXpnoqX0Twy7tG8MTa2@dpg-d6hm0ljuibrs73a0unp0-a/biblioteca_fcmz}
spring.datasource.username=${biblioteca_fcmz_user}
spring.datasource.password=${3EyfGBzSbUzADCXpnoqX0Twy7tG8MTa2}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

logging.level.org.springframework.security=DEBUG